mode: ContinuousDelivery
branches:
  develop:
    regex: ^dev(elop)?(ment)?$
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    source-branches: []
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 0
  main:
    regex: ^main$
    increment: Major
    label: ''
    is-main-branch: true
    source-branches: ['release', 'hotfix']
  release:
    regex: ^release$
    increment: Major
    label: release
    source-branches: ['dev', 'hotfix']
  feature:
    regex: ^feature[/-].+$
    increment: Patch
    label: feature
  hotfix:
    regex: ^hotfix([/-].+)?$
    increment: Patch
    label: hotfix
ignore:
  sha: []
