mode: Mainline
branches:
  main:
    increment: Major
    tag: ''
    prevent-increment-of-merged-branch-version: true
    regex: main
    source-branches: ['release', 'hotfix']
  release:
    increment: Major
    tag: 'rc'
    prevent-increment-of-merged-branch-version: true
    regex: release[/-]
    source-branches: ['dev', 'hotfix']
  dev:
    increment: Minor
    tag: 'dev'
    prevent-increment-of-merged-branch-version: true
    regex: dev
    source-branches: ['feature']
  feature:
    increment: Minor
    tag: 'feature'
    regex: feature[/-]
    source-branches: ['dev']
  hotfix:
    increment: Patch
    tag: 'hotfix'
    regex: hotfix[/-]
    source-branches: ['main', 'release']
ignore:
  sha: []
commit-message-incrementing: Enabled
