mode: Mainline
branches:
  main:
    regex: ^main$
    increment: Major
    is-mainline: true
    tag: ''
  dev:
    regex: ^dev$
    increment: Minor
    tag: dev
    source-branches: ['main']
  sprint:
    regex: ^sprint-.+$
    increment: Patch
    tag: sprint
    source-branches: ['dev']
  feature:
    regex: ^feature[/-].+$
    increment: Patch
    tag: feature
    source-branches: ['sprint', 'dev']
  hotfix:
    regex: ^hotfix([/-].+)?$
    increment: Patch
    tag: hotfix
    source-branches: ['main']
ignore:
  sha: []
merge-message-strategy: MergeMessage
