# GitVersion.yml
# For more options, see the official documentation at https://gitversion.net/docs/reference/configuration

mode: ContinuousDelivery
assembly-versioning-scheme: MajorMinorPatch
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'

branches:
  # The main branch will create a new minor version upon merge.
  main:
    regex: ^(main|master)$
    increment: Major
    tag: '' # Empty tag for production releases
  
  # The development branch receives incremental versions.
  develop:
    regex: ^dev(elop)?(ment)?$
    increment: Minor
    tag: dev
  
  # Release branches are for final testing before a production release.
  release:
    regex: ^release?[/-]
    increment: Major
    tag: release
    is-release-branch: true
    source-branches: ['main', 'develop']
  
  # Hotfix branches are for critical patches to the main branch.
  hotfix:
    regex: ^hotfix?[/-]
    increment: Patch
    tag: beta
    source-branches: ['main']
  
  # Feature branches use the branch name as a pre-release tag.
  feature:
    regex: ^feature?[/-]
    increment: Minor
    tag: useBranchName
    source-branches: ['develop', 'main']
  
  # # Pull Request branches get tagged with 'pull-request'.
  # pull-request:
  #   regex: ^(pull-request|pr)[/-]
  #   tag: pull-request
  #   mode: ContinuousDeployment