mode: Mainline
branches:
  main:
    regex: ^main$
    increment: Major
    is-mainline: true
    tag: ''
    source-branches: ['QA', 'hotfix']
  QA:
    regex: ^QA$ 
    increment: Major # release should come
    tag: release
    source-branches: ['dev', 'hotfix']
  dev:
    regex: ^dev$
    increment: Minor
    tag: sprint
    source-branches: ['feature']
  feature:
    regex: ^feature[/-].+$
    increment: Patch
    tag: feature
  hotfix:
    regex: ^hotfix([/-].+)?$
    increment: Patch
    tag: hotfix
ignore:
  sha: []
merge-message-strategy: MergeMessage
