mode: Mainline
branches:
  main:
    regex: ^main$
    increment: Major
    is-mainline: true
    tag: ''
  QA:
    regex: ^QA$ 
    increment: Major
    tag: release
    source-branches: ['main']
  dev:
    regex: ^dev$
    increment: Minor
    tag: sprint
    source-branches: ['main']
  feature:
    regex: ^feature[/-].+$
    increment: Patch
    tag: feature
    source-branches: ['main', 'dev']
  hotfix:
    regex: ^hotfix([/-].+)?$
    increment: Patch
    tag: hotfix
    source-branches: ['main']
ignore:
  sha: []
merge-message-strategy: MergeMessage
