mode: ContinuousDelivery
branches:
  main:
    increment: Major
    label: ''
    regex: main
    source-branches: ['release', 'hotfix']
  release:
    increment: Major
    label: 'rc'
    regex: release[/-]
    source-branches: ['dev', 'hotfix']
  dev:
    increment: Minor
    label: 'dev'
    regex: dev
    source-branches: ['feature']
  feature:
    increment: Minor
    label: 'feature'
    regex: feature[/-]
    source-branches: ['dev']
  hotfix:
    increment: Patch
    label: 'hotfix'
    regex: hotfix[/-]
    source-branches: ['main', 'release']
ignore:
  sha: []
commit-message-incrementing: Enabled
