name: Use Central GitVersion Workflow

on:
  push:
    branches: [main, release, dev, feature/**]
  pull_request:
    branches: [main, release, dev, feature/**]


jobs:

  call-versioning-other-branches:
    # if: (!contains('refs/heads/main,refs/heads/release', github.ref))
    uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/gitversion.yml@feature/testing_gitversion
# commit msg -- Merge feature/xyz into main +semver: major

  debug-context:
    runs-on: ubuntu-latest
    needs: call-main-tagging
    steps:
      - name: Print GitHub context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event_name: ${{ github.event_name }}"

