name: Use Central GitVersion Workflow

on:
  push:
    branches: [main, QA, dev, feature/**]
  pull_request:
    branches: [main, QA, dev, feature/**]


jobs:

  call-main-tagging:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/QA'
    uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/tagging.yml@feature/testing_gitversion


  call-versioning-main:
    if: (contains('refs/heads/main,refs/heads/QA', github.ref) || contains('main,QA', github.base_ref)) && needs.call-main-tagging.outputs.needs_tag == 'false'
    needs: call-main-tagging
    uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/gitversion.yml@feature/testing_gitversion


  call-versioning-other-branches:
    if: github.ref != 'refs/heads/main'
    uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/gitversion.yml@feature/testing_gitversion
# commit msg -- Merge feature/xyz into main +semver: major

  debug-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "needs_tag: ${{ needs.call-main-tagging.outputs.needs_tag }}"

