name: Use Central GitVersion Workflow

on:
  push:
    branches: [main, dev, sprint, feature/**]
  # pull_request:
  #   branches: [main, dev, sprint, feature/**]

jobs:
  call-versioning:
    uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/gitversion.yml@feature/testing_gitversion

