name: Use Central GitVersion Workflow

on:
  push:
    branches: [main, dev, sprint, feature/**]
  # pull_request:
  #   branches: [main, dev, sprint, feature/**]

jobs:
  call-versioning:
    uses: your-org/org-workflows/.github/workflows/gitversion.yml@main
