name: Use Central GitVersion Workflow

on:
  push:
    branches: [main, release, develop, dev, feature/**]
  # pull_request:
  #   branches: [main, release, dev, feature/**]


jobs:

  # call-main-tagging:
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
  #   uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/tagging.yml@feature/testing_gitversion



  # call-versioning-main-or-qa:
  #   if: (contains('refs/heads/main,refs/heads/release', github.ref) || contains('main,release', github.base_ref)) && needs.call-main-tagging.outputs.needs_tag == 'false'
  #   # needs: call-main-tagging
  #   uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/gitversion.yml@feature/testing_gitversion



  call-versioning-other-branches:
    # if: (!contains('refs/heads/main,refs/heads/release', github.ref))
    uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/gitversion.yml@feature/testing_gitversion
# commit msg -- Merge feature/xyz into main +semver: major

  # debug-context:
  #   runs-on: ubuntu-latest
  #   needs: call-main-tagging
  #   steps:
  #     - name: Print GitHub context
  #       run: |
  #         echo "github.ref: ${{ github.ref }}"
  #         echo "github.base_ref: ${{ github.base_ref }}"
  #         echo "github.event_name: ${{ github.event_name }}"
  #         echo "needs_tag: ${{ needs.call-main-tagging.outputs.needs_tag }}"

