name: Use Central GitVersion Workflow

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
      - 'feature/**'
  # pull_request:
  #   branches:
  #     - main
  #     - develop
  #     - 'release/**'
      
 
jobs:

  call-versioning-other-branches:
    uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/final.yml@feature/testing_gitversion



