name: Use Central GitVersion Workflow

on:
  push:
    branches:
      - main
      - dev
      - release
      - 'hotfix/**'
      - 'feature/**'
      
 
jobs:

  call-versioning-other-branches:
    if: github.event.pull_request.head.ref == ''
    uses: Basic-organisation-flow-template/standard_central_repo/.github/workflows/final.yml@feature/testing_gitversion



